# Generated by Django 4.0.4 on 2022-04-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnconfirmedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='person.readonlydb')),
                ('person', models.ManyToManyField(blank=True, null=True, related_name='transaction', to='person.person')),
            ],
        ),
    ]
