# Generated by Django 4.0.4 on 2022-04-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonToDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnconfirmedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='person.readonlydb')),
                ('person_to_add', models.ManyToManyField(blank=True, null=True, related_name='transaction_add', to='person.person')),
                ('person_to_delete', models.ManyToManyField(blank=True, null=True, related_name='transaction_delete', to='person.persontodelete')),
            ],
        ),
        migrations.AddField(
            model_name='readonlydb',
            name='person_to_delete',
            field=models.ManyToManyField(blank=True, null=True, related_name='db', to='person.persontodelete'),
        ),
    ]
